#!/bin/bash

set -e
if [ -d ~/.rbenv ]
then
    cd ~/.rbenv && git pull
    git -C "$(rbenv root)"/plugins/ruby-build pull
else
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    eval "$(~/.rbenv/bin/rbenv init - zsh)"
    git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
fi

latest_ruby_version(){
  rbenv install -l 2>/dev/null | rg '^\d' | tail -1
}

echo "Installing latest Ruby (version $(latest_ruby_version))..."
if rbenv versions | rg "$(latest_ruby_version)" > /dev/null; then
  echo "Already installed"
else
  rbenv install "$(latest_ruby_version)"
  rbenv global "$(latest_ruby_version)"
  gem install solargraph htmlbeautifier
fi
