#!/bin/bash

set -e

echo 'Installing NodeJS 16 and Yarn...'
if ! type "fnm" &> /dev/null; then
  curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "~/.fnm" --skip-shell
  export PATH=/home/martin/.fnm:$PATH
  eval "`fnm env`"

  fnm install 18
fi

if ! type "prettier" &> /dev/null; then
  npm install -g prettier
fi

if ! type "yarn" &> /dev/null; then
  npm install -g yarn
fi
